###############
//add new category of menu items...
post http://localhost:5000/data/addcategory


###############
#get all of the item's categories available in menu
get http://localhost:5000/data/api/menuitems


###############
#get all customers detail......
get http://localhost:5000/customer/api/customers


##############
//addMenuItems....
post http://localhost:5000/data/addmenuitems
content-type: application/json

{
    "category": 1,
    "name":"Chapli Zinger",
    "price":"300"
}

###
//delete items from Menu......
get http://localhost:5000/data/removeitem/1

##############
//update Menu Item
post http://localhost:5000/data/edititem
content-type: application/json

{
    "itemID":"8",
    "itemCategoryID": "1",
    "itemName":"Star Burger",
    "itemPrice":"250"
}

####################
//add new employ

post http://localhost:5000/employ/newemploy
content-type: application/json

{
    "name":"sufiyan",
    "userName":"saifi123",
    "password":"saifi123",
    "contact":"0300000000",
    "address":"House No ......",
    "role":"manager"
}

#########################
//get all employ....
get http://localhost:5000/employ/allemploy

#############3
//delete an employ......
post http://localhost:5000/employ/deleteemploy/4f2141498c63a565ed2f0807e21ba71c


###################3
//update employ.......
post http://localhost:5000/employ/updateemploy
content-type: application/json

{
    "employID":"acdd31c53a571cc25b733c9fc9b62145",
    "name":"sufiyan",
    "userName":"saifi123",
    "password":"saifi123",
    "contact":"0300000000",
    "address":"House No ......",
    "role":"cashier"
}


####################
//add new customer

post http://localhost:5000/customer/newcustomer
content-type: application/json

{
    "name":"Haseeb",
    "userName":"Haseeb123",
    "password":"haseeb123",
    "contact":"0300000000",
    "address":"Pakpattan"
}

####################
//update customer

post http://localhost:5000/customer/updatecustomer
content-type: application/json

{
    "customerID":"2b5163f4884d2e5e653ad0fe7c6ee990",
    "name":"Haseeb",
    "userName":"Haseeb123",
    "password":"haseeb123",
    "contact":"0300000000",
    "address":"LAhore"
}

#################
///delete customer..............
post http://localhost:5000/customer/deletecustomer/2b5163f4884d2e5e653ad0fe7c6ee990