###############
//add new category of menu items...
post http://localhost:5000/data/addcategory


###############
#get all of the item's categories available in menu
get http://localhost:5000/data/api/menuitems


###############
#get all customers detail......
get http://localhost:5000/customer/api/customers


##############
//addMenuItems....
post http://localhost:5000/data/addmenuitems
content-type: application/json

{
    "category": 1,
    "name":"Chapli Zinger",
    "price":"300"
}

###
//delete items from Menu......
get http://localhost:5000/data/removeitem/1

##############
//update Menu Item
post http://localhost:5000/data/edititem
content-type: application/json

{
    "itemID":"8",
    "itemCategoryID": "1",
    "itemName":"Star Burger",
    "itemPrice":"250"
}

####################
//add new employ

post http://localhost:5000/employ/newemploy
content-type: application/json

{
    "name":"sufiyan",
    "userName":"saifi12",
    "password":"saifi123",
    "contact":"0300000000",
    "address":"House No ......",
    "role":"manager"
}

#########################
//get all employ....
get http://localhost:5000/employ/allemploy

#############3
//delete an employ......
post http://localhost:5000/employ/deleteemploy/4f2141498c63a565ed2f0807e21ba71c


###################3
//update employ.......
post http://localhost:5000/employ/updateemploy
content-type: application/json

{
    "employID":"acdd31c53a571cc25b733c9fc9b62145",
    "name":"sufiyan",
    "userName":"Saifi123",
    "password":"saifi123",
    "contact":"0300000000",
    "address":"House No ......",
    "role":"cashier"
}


####################
//add new customer

post http://localhost:5000/customer/newcustomer
content-type: application/json

{
    "name":"Haseeb",
    "userName":"Haseeb123",
    "password":"haseeb123",
    "contact":"0300000000",
    "address":"Pakpattan"
}

####################
//update customer

post http://localhost:5000/customer/updatecustomer
content-type: application/json

{
    "customerID":"03342f580c4750777aeb4ca7ec5908de",
    "name":"usama",
    "userName":"usama",
    "contact":"0300000000",
    "address":"LAhore"
}

#################
///login user..............
post http://localhost:5000/auth/user/login
content-type: application/json

{

    "userName":"admin12",
    "password":"admin123"
}

#####################
///place order

post http://localhost:5000/order/placeorder
content-type: application/json

{
    "customerID":"4d1408a6fbcf30bf2abc4e18ff33d8dc",
    "totalPrice":"1000"
}

#############
//get orders...........
get http://localhost:5001/order/orders/6a430b36708ee576065f7befba5785a5


################
//update status

post http://localhost:5001/order/orders/updatestatus
content-type: application/json

{
    "orderID":"0647cec92ebe5001281f8b703c3013c2"
}

#############
//get orders...........
get http://localhost:5001/order/orders/finishedorders

