###############
//add new category of menu items...
post http://localhost:5000/data/addcategory


###############
#get all of the item's categories available in menu
get http://localhost:5000/data/api/menuitems


###############
#get all customers detail......
get http://localhost:5000/data/api/customers


##############
//addMenuItems....
post http://localhost:5000/data/addmenuitems
content-type: application/json

{
    "itemCategoryID": 1,
    "itemName":"Patty Zinger",
    "itemPrice":"200"
}

###
//delete items from Menu......
get http://localhost:5000/data/removeitem/1

##############
//update Menu Item
post http://localhost:5000/data/edititem
content-type: application/json

{
    "itemID":"8",
    "itemCategoryID": "1",
    "itemName":"Star Burger",
    "itemPrice":"250"
}